/* ============================================================
   SERVICES DATA — All 20 projects
   ============================================================ */
const SERVICES_DATA = [
  // ══════ 1-ROOM ══════
  {
    id: 'studio-minimalism',
    rooms: 1,
    style: 'minimalism',
    title: 'Однокомнатная — Минимализм',
    shortDesc: 'Лаконичное пространство без лишних деталей, где каждый элемент несёт смысл.',
    desc: 'Минимализм — это философия жизни, выраженная в пространстве. Мы создаем чистые линии, нейтральную палитру и функциональную мебель. Каждый предмет тщательно отобран и занимает своё место. Результат — спокойное, вдохновляющее пространство.',
    price: 'от 380 000 ₽',
    priceVal: 380000,
    term: '2–3 месяца',
    area: 'от 35 м²',
    image: 'images/project_studio.png',
    images: ['images/project_studio.png','images/about_interior.png','images/hero_interior.png','images/project_scandi.png'],
    features: ['Дизайн-проект с 3D-визуализацией','Подбор мебели и декора','Авторский надзор за ремонтом','Монтаж освещения','Чистовая отделка стен и полов','Установка сантехники'],
    materials: [
      {icon:'🪵', name:'Паркетная доска Barlinek', desc:'Дуб натуральный, 14 мм'},
      {icon:'🪟', name:'Матовые стеклянные панели', desc:'Перегородки и двери'},
      {icon:'🎨', name:'Краска Dulux Ambiance', desc:'Интерьерная, матовая'},
      {icon:'🛁', name:'Сантехника Grohe Essence', desc:'Хром, premium линейка'},
    ],
    reviews: [
      {name:'Анна К.', role:'ЖК «Символ»', text:'Потрясающая работа! Маленькая квартира превратилась в стильное, просторное жилище.', img:'images/client_avatar1.png'},
      {name:'Дмитрий Р.', role:'ЖК «Огни»', text:'Отличная команда, чёткое соблюдение сроков. Минимализм получился именно таким, о каком я мечтал.', img:'images/client_avatar2.png'},
    ]
  },
  {
    id: 'studio-scandinavian',
    rooms: 1,
    style: 'scandinavian',
    title: 'Однокомнатная — Скандинавский',
    shortDesc: 'Уют, натуральные материалы и тёплый свет в скандинавской эстетике.',
    desc: 'Скандинавский стиль — это гармония природы и человека. Светлые стены, деревянные акценты, мягкий текстиль и зелёные растения создают атмосферу уюта. Мы воплощаем философию «hygge» в каждом пространстве.',
    price: 'от 420 000 ₽',
    priceVal: 420000,
    term: '2,5–3,5 месяца',
    area: 'от 35 м²',
    image: 'images/project_scandi.png',
    images: ['images/project_scandi.png','images/project_studio.png','images/about_interior.png','images/hero_interior.png'],
    features: ['Дизайн-проект полного цикла','3D-визуализация всех помещений','Подбор скандинавской мебели','Натуральный текстиль и декор','Освещение Bolig Nordlux','Авторский надзор'],
    materials: [
      {icon:'🌿', name:'Светлый дуб', desc:'Массив, необработанный'},
      {icon:'🧶', name:'Натуральный лён', desc:'Шторы и текстиль'},
      {icon:'🎨', name:'Белая краска Tikkurila', desc:'Ultra Matt, интерьерная'},
      {icon:'🪴', name:'Живые растения', desc:'Подбор и озеленение'},
    ],
    reviews: [
      {name:'Екатерина С.', role:'ЖК «Гринвуд»', text:'Хюгге — именно это я и хотела! Тепло, уютно, красиво. Спасибо команде DesignPro.', img:'images/client_avatar3.png'},
    ]
  },
  {
    id: 'studio-modern',
    rooms: 1,
    style: 'modern',
    title: 'Однокомнатная — Современный стиль',
    shortDesc: 'Смелые формы, фактурные поверхности и технологичные решения.',
    desc: 'Современный интерьер — это баланс между эстетикой и функциональностью. Мы используем смелые цветовые акценты, интересные материалы и продуманную эргономику. Пространство выглядит актуально и останется таким на годы.',
    price: 'от 450 000 ₽',
    priceVal: 450000,
    term: '3–4 месяца',
    area: 'от 38 м²',
    image: 'images/hero_interior.png',
    images: ['images/hero_interior.png','images/project_studio.png','images/about_interior.png','images/project_scandi.png'],
    features: ['Полный дизайн-проект','Подбор мебели и техники','Умный дом — базовый пакет','Встроенные светильники','Авторский надзор','Финальная уборка'],
    materials: [
      {icon:'🔩', name:'Матовый металл', desc:'Акцентные элементы'},
      {icon:'🪵', name:'Венге тёмный', desc:'Шпон для корпусной мебели'},
      {icon:'💡', name:'Диммируемые LED', desc:'Система освещения Philips Hue'},
      {icon:'🏗️', name:'Штукатурка Marmorino', desc:'Декоративная, венецианская'},
    ],
    reviews: [
      {name:'Михаил П.', role:'ЖК «Северный»', text:'Сделали всё под ключ, включая умный дом. Результат — выше всяких ожиданий!', img:'images/client_avatar2.png'},
    ]
  },
  {
    id: 'studio-loft',
    rooms: 1,
    style: 'loft',
    title: 'Однокомнатная — Лофт',
    shortDesc: 'Открытое пространство, кирпич, металл и индустриальный характер.',
    desc: 'Лофт — стиль для тех, кто ценит свободу и характер. Открытые потолки, кирпичные стены, металлические конструкции и смешение материалов создают уникальную атмосферу. Мы бережно прорабатываем каждую деталь.',
    price: 'от 390 000 ₽',
    priceVal: 390000,
    term: '2,5–3 месяца',
    area: 'от 40 м²',
    image: 'images/project_loft.png',
    images: ['images/project_loft.png','images/hero_interior.png','images/project_studio.png','images/about_interior.png'],
    features: ['Демонтаж до бетона','Кирпичная кладка / декор','Металлические перегородки','Лофтовое освещение Edison','Подбор индустриальной мебели','Авторский надзор'],
    materials: [
      {icon:'🧱', name:'Лицевой кирпич', desc:'Ручная кладка и облицовка'},
      {icon:'⚙️', name:'Чёрный металл', desc:'Трубы, профиль, фурнитура'},
      {icon:'🪵', name:'Состаренное дерево', desc:'Паллетная доска и массив'},
      {icon:'💡', name:'Лампы Эдисона', desc:'Vintage E27, фурнитура Loft Concept'},
    ],
    reviews: [
      {name:'Анна М.', role:'ЖК «Парк Авеню»', text:'Лофт получился аутентичным и стильным. Соседи завидуют!', img:'images/client_avatar1.png'},
    ]
  },
  {
    id: 'studio-neoclassic',
    rooms: 1,
    style: 'neoclassic',
    title: 'Однокомнатная — Неоклассика',
    shortDesc: 'Элегантность классики в современном прочтении.',
    desc: 'Неоклассика соединяет монументальность классического стиля с современными технологиями и комфортом. Лепнина, симметрия, бархат и мрамор — всё это органично вписывается в концепцию современного жилья.',
    price: 'от 550 000 ₽',
    priceVal: 550000,
    term: '3–5 месяцев',
    area: 'от 40 м²',
    image: 'images/project_neoclassic.png',
    images: ['images/project_neoclassic.png','images/hero_interior.png','images/about_interior.png','images/project_scandi.png'],
    features: ['Лепнина из полиуретана','Мраморные полы и поверхности','Хрустальные люстры','Бархатный текстиль','Позолоченная фурнитура','Авторский надзор'],
    materials: [
      {icon:'🏛️', name:'Мрамор Calacatta', desc:'Полы и столешницы'},
      {icon:'✨', name:'Лепнина Orac Decor', desc:'Карнизы, розетки, молдинги'},
      {icon:'🕯️', name:'Хрусталь', desc:'Люстры и светильники Swarovski'},
      {icon:'🧶', name:'Бархат Nobilis', desc:'Портьеры и обивка'},
    ],
    reviews: [
      {name:'Екатерина С.', role:'ЖК «Золотые ключи»', text:'Потрясающий результат! Чувствую себя, как в пятизвёздочном отеле.', img:'images/client_avatar3.png'},
    ]
  },

  // ══════ 2-ROOM ══════
  {
    id: 'two-minimalism',
    rooms: 2,
    style: 'minimalism',
    title: 'Двухкомнатная — Минимализм',
    shortDesc: 'Функциональное зонирование без лишнего: только самое важное.',
    desc: 'В двухкомнатной квартире минимализм раскрывается во всей красе. Грамотное зонирование open-plan гостиной и кухни, встроенные системы хранения и продуманная эргономика делают каждый метр полезным.',
    price: 'от 620 000 ₽',
    priceVal: 620000,
    term: '3–4 месяца',
    area: 'от 55 м²',
    image: 'images/project_studio.png',
    images: ['images/project_studio.png','images/hero_interior.png','images/about_interior.png','images/project_loft.png'],
    features: ['Дизайн-проект 2 комнаты + кухня','Встроенные шкафы-купе','Open-plan гостиная-кухня','LED-подсветка по периметру','Авторский надзор','Меблировка под ключ'],
    materials: [
      {icon:'🪵', name:'Ламинат Pergo', desc:'33 класс, 12 мм, дуб'},
      {icon:'🎨', name:'Декоративная штукатурка', desc:'Baumit Nanopor Top'},
      {icon:'🛁', name:'Сантехника Ideal Standard', desc:'Коллекция Connect Air'},
      {icon:'💡', name:'Трековые светильники', desc:'Maytoni Technical, IP20'},
    ],
    reviews: [
      {name:'Анна М.', role:'ЖК «Баркли»', text:'Двушка за 55 кв стала ощущаться как 80. Умные решения по хранению — просто находка!', img:'images/client_avatar1.png'},
    ]
  },
  {
    id: 'two-scandinavian',
    rooms: 2,
    style: 'scandinavian',
    title: 'Двухкомнатная — Скандинавский',
    shortDesc: 'Тепло и уют для молодой семьи в скандинавском духе.',
    desc: 'Идеальное решение для молодой семьи: светлые пространства, функциональная детская и уютная гостиная. Натуральные материалы, мягкий текстиль и тщательно подобранное освещение создают идеальную атмосферу для жизни.',
    price: 'от 680 000 ₽',
    priceVal: 680000,
    term: '3–4 месяца',
    area: 'от 55 м²',
    image: 'images/project_scandi.png',
    images: ['images/project_scandi.png','images/project_studio.png','images/about_interior.png','images/hero_interior.png'],
    features: ['Дизайн гостиной и спальни','Детская комната','Скандинавская мебель','Натуральный текстиль','Авторский надзор','Озеленение'],
    materials: [
      {icon:'🌿', name:'Массив сосны', desc:'Мебель IKEA и аналоги'},
      {icon:'🧶', name:'Хлопковый трикотаж', desc:'Пледы, подушки Ikea/H&M Home'},
      {icon:'🎨', name:'Тиккурила Евро 7', desc:'Белая и пастельные тона'},
      {icon:'🪴', name:'Фикус, монстера', desc:'Живые растения в подборке'},
    ],
    reviews: [
      {name:'Дмитрий Р.', role:'ЖК «Испанские кварталы»', text:'Взяли проект для семьи с ребёнком. Очень функционально и красиво!', img:'images/client_avatar2.png'},
    ]
  },
  {
    id: 'two-modern',
    rooms: 2,
    style: 'modern',
    title: 'Двухкомнатная — Современный стиль',
    shortDesc: 'Технологичный интерьер с эффектными цветовыми акцентами.',
    desc: 'Современный стиль для двухкомнатной квартиры — это динамика форм, богатая текстура и цветовые акценты. Мы создаём интерьер, который живёт и дышит вместе с вами.',
    price: 'от 720 000 ₽',
    priceVal: 720000,
    term: '3,5–5 месяцев',
    area: 'от 60 м²',
    image: 'images/project_two_room.png',
    images: ['images/project_two_room.png','images/hero_interior.png','images/project_loft.png','images/about_interior.png'],
    features: ['Дизайн-проект + 3D','Умный дом базовый','Встроенная техника AEG','Панорамные шторы','Авторский надзор','Финальный стайлинг'],
    materials: [
      {icon:'🏗️', name:'Микроцемент', desc:'Покрытие для стен и пола'},
      {icon:'🔩', name:'Латунь Brushed', desc:'Фурнитура и смесители'},
      {icon:'💡', name:'Philips Hue', desc:'Умное освещение'},
      {icon:'🪵', name:'МДФ с шпоном ореха', desc:'Фасады мебели'},
    ],
    reviews: [
      {name:'Михаил П.', role:'ЖК «Level»', text:'Свет управляется с телефона, все встроено — космос! Очень доволен.', img:'images/client_avatar2.png'},
    ]
  },
  {
    id: 'two-loft',
    rooms: 2,
    style: 'loft',
    title: 'Двухкомнатная — Лофт',
    shortDesc: 'Промышленный шик в просторной двухкомнатной квартире.',
    desc: 'Просторная двухкомнатная квартира в стиле лофт — открытые пространства, высокие потолки и индустриальные детали. Мы создаём интерьер с характером и историей.',
    price: 'от 660 000 ₽',
    priceVal: 660000,
    term: '3–4 месяца',
    area: 'от 58 м²',
    image: 'images/project_loft.png',
    images: ['images/project_loft.png','images/project_two_room.png','images/about_interior.png','images/hero_interior.png'],
    features: ['Открытые потолки с балками','Кирпичные акценты','Металлические лестницы','Промышленное освещение','Меблировка в стиле лофт','Авторский надзор'],
    materials: [
      {icon:'🧱', name:'Декоративный кирпич', desc:'Loft Stone, Экокирпич'},
      {icon:'🪵', name:'Брашированный дуб', desc:'Полы и лестница'},
      {icon:'⚙️', name:'Чёрная сталь', desc:'Перила, полки, декор'},
      {icon:'💡', name:'Трубчатый светильник', desc:'Industrial style, GU10'},
    ],
    reviews: [
      {name:'Екатерина С.', role:'Апартаменты «Loft 17»', text:'Настоящий нью-йоркский лофт в центре Москвы. Бесподобно!', img:'images/client_avatar3.png'},
    ]
  },
  {
    id: 'two-neoclassic',
    rooms: 2,
    style: 'neoclassic',
    title: 'Двухкомнатная — Неоклассика',
    shortDesc: 'Аристократичный интерьер с классическими пропорциями.',
    desc: 'Неоклассика в двухкомнатной квартире — это симметрия, декоративные молдинги, натуральные ткани и мраморные поверхности. Интерьер вне времени.',
    price: 'от 850 000 ₽',
    priceVal: 850000,
    term: '4–6 месяцев',
    area: 'от 60 м²',
    image: 'images/project_neoclassic.png',
    images: ['images/project_neoclassic.png','images/project_two_room.png','images/hero_interior.png','images/about_interior.png'],
    features: ['Лепные карнизы и молдинги','Мраморные полы','Хрустальные люстры Bohemia','Классическая мебель','Шёлковые портьеры','Авторский надзор'],
    materials: [
      {icon:'🏛️', name:'Мрамор Nero Marquina', desc:'Полы и каминная полка'},
      {icon:'✨', name:'Лепнина Orac Decor', desc:'Полный комплект декора'},
      {icon:'🧶', name:'Шёлк натуральный', desc:'Шторы и обивка мебели'},
      {icon:'🪟', name:'Двери Profil Doors', desc:'Эмаль, стиль классика'},
    ],
    reviews: [
      {name:'Анна К.', role:'ЖК «Дворянское гнездо»', text:'Интерьер как из журнала ELLE Decoration. Мечта!', img:'images/client_avatar1.png'},
    ]
  },

  // ══════ 3-ROOM ══════
  {
    id: 'three-minimalism',
    rooms: 3,
    style: 'minimalism',
    title: 'Трёхкомнатная — Минимализм',
    shortDesc: 'Просторный семейный минимализм — всё на своём месте.',
    desc: 'Трёхкомнатная квартира в стиле минимализм — идеал для семьи, ценящей пространство и порядок. Продуманное зонирование, встроенные системы хранения, нейтральная палитра.',
    price: 'от 950 000 ₽',
    priceVal: 950000,
    term: '4–5 месяцев',
    area: 'от 75 м²',
    image: 'images/hero_interior.png',
    images: ['images/hero_interior.png','images/project_studio.png','images/about_interior.png','images/project_scandi.png'],
    features: ['Полный дизайн-проект','Гардеробная комната','Open-plan кухня-гостиная','Детская и спальня','Авторский надзор','Меблировка под ключ'],
    materials: [
      {icon:'🪵', name:'Кварцвиниловый ламинат', desc:'Pergo Extreme, 6 мм'},
      {icon:'🎨', name:'Матовая краска', desc:'Dulux Matt Plus'},
      {icon:'💡', name:'Скрытые карнизы', desc:'Освещение Eglo Flex'},
      {icon:'🛁', name:'Ванная комната', desc:'Villeroy & Boch Complete'},
    ],
    reviews: [
      {name:'Дмитрий Р.', role:'ЖК «Символ», Москва', text:'Семья в восторге! Три комнаты стали идеальным домом.', img:'images/client_avatar2.png'},
    ]
  },
  {
    id: 'three-scandinavian',
    rooms: 3,
    style: 'scandinavian',
    title: 'Трёхкомнатная — Скандинавский',
    shortDesc: 'Уютный дом для всей семьи в любимом скандинавском духе.',
    desc: 'Этот проект воплощает лучшее из скандинавской эстетики: большие окна, светлые поверхности, натуральное дерево, растения и умелое сочетание цветовых акцентов.',
    price: 'от 1 050 000 ₽',
    priceVal: 1050000,
    term: '4–6 месяцев',
    area: 'от 80 м²',
    image: 'images/project_scandi.png',
    images: ['images/project_scandi.png','images/hero_interior.png','images/about_interior.png','images/project_studio.png'],
    features: ['Дизайн 3-х комнат полностью','Детская с игровой зоной','Скандинавская мебель','Тёплые полы в ванной','Умное освещение','Авторский надзор'],
    materials: [
      {icon:'🌿', name:'Дуб беленый', desc:'Паркетная доска 15 мм'},
      {icon:'🧶', name:'Шерстяные ковры', desc:'Rya Rug, Дания'},
      {icon:'🪴', name:'Фитодизайн', desc:'Подбор 20+ растений'},
      {icon:'💡', name:'Louis Poulsen', desc:'Подвесные светильники PH'},
    ],
    reviews: [
      {name:'Михаил П.', role:'ЖК «Гринвуд»', text:'Как в Стокгольме дома — натурально и красиво!', img:'images/client_avatar2.png'},
    ]
  },
  {
    id: 'three-modern',
    rooms: 3,
    style: 'modern',
    title: 'Трёхкомнатная — Современный стиль',
    shortDesc: 'Технологичность и стиль в большой семейной квартире.',
    desc: 'Современный дизайн трёхкомнатной квартиры с функциями умного дома. Панорамные окна, акустические панели в кабинете, сенсорные выключатели — всё для комфорта.',
    price: 'от 1 100 000 ₽',
    priceVal: 1100000,
    term: '4–6 месяцев',
    area: 'от 82 м²',
    image: 'images/project_two_room.png',
    images: ['images/project_two_room.png','images/hero_interior.png','images/project_loft.png','images/about_interior.png'],
    features: ['Умный дом расширенный','Мультирум аудиосистема','Кабинет с акустикой','Кухня Aster Cucine','Авторский надзор','Финальный стайлинг'],
    materials: [
      {icon:'💡', name:'Умное освещение Casambi', desc:'Bluetooth Mesh система'},
      {icon:'🔊', name:'Sonos In-Ceiling', desc:'Встроенная акустика'},
      {icon:'🏗️', name:'Керамогранит 120×60', desc:'Ariostea Ultra Pietre'},
      {icon:'🪵', name:'Орех американский', desc:'Фасады кухни на заказ'},
    ],
    reviews: [
      {name:'Анна М.', role:'ЖК «Headliner»', text:'Управляю квартирой с телефона из любой точки мира. Технологии на максимум!', img:'images/client_avatar1.png'},
    ]
  },
  {
    id: 'three-loft',
    rooms: 3,
    style: 'loft',
    title: 'Трёхкомнатная — Лофт',
    shortDesc: 'Большая лофт-квартира с открытой планировкой и характером.',
    desc: 'Трёхкомнатный лофт — масштаб, пространство и стиль. Высокие потолки, открытые коммуникации, кирпичные стены и стеклянные перегородки создают незабываемую атмосферу.',
    price: 'от 980 000 ₽',
    priceVal: 980000,
    term: '4–5 месяцев',
    area: 'от 85 м²',
    image: 'images/project_loft.png',
    images: ['images/project_loft.png','images/project_two_room.png','images/about_interior.png','images/hero_interior.png'],
    features: ['Открытая планировка','Стеклянные перегородки','Декоративный кирпич','Металлические элементы','Промышленная кухня','Авторский надзор'],
    materials: [
      {icon:'🧱', name:'Кирпич Lode', desc:'Клинкерный облицовочный'},
      {icon:'🪟', name:'Стекло Clear', desc:'Перегородки 10 мм'},
      {icon:'⚙️', name:'Профиль Loft Concept', desc:'Чёрный металл RAL 9005'},
      {icon:'🪵', name:'Паллетная доска', desc:'Состаренное дерево, лак'},
    ],
    reviews: [
      {name:'Екатерина С.', role:'Апартаменты «Мельница»', text:'Потрясающее пространство. Лофт в 3 комнаты — это совсем другой уровень!', img:'images/client_avatar3.png'},
    ]
  },
  {
    id: 'three-neoclassic',
    rooms: 3,
    style: 'neoclassic',
    title: 'Трёхкомнатная — Неоклассика',
    shortDesc: 'Роскошный классический интерьер для большой семьи.',
    desc: 'Три комнаты в стиле неоклассика — это симфония красоты и элегантности. Каждая комната имеет свой характер, объединённый единой классической концепцией.',
    price: 'от 1 400 000 ₽',
    priceVal: 1400000,
    term: '5–7 месяцев',
    area: 'от 90 м²',
    image: 'images/project_neoclassic.png',
    images: ['images/project_neoclassic.png','images/hero_interior.png','images/project_two_room.png','images/about_interior.png'],
    features: ['Лепнина по всей квартире','Каминный зал','Итальянская мебель Selva','Шёлковые обои','Золотая фурнитура','Авторский надзор'],
    materials: [
      {icon:'🏛️', name:'Мрамор Bianco Carrara', desc:'Полы гостиной и прихожей'},
      {icon:'✨', name:'Лепнина Stucco Veneziano', desc:'Полный декор потолков'},
      {icon:'🧶', name:'Шёлковые обои Elitis', desc:'Французские тканевые обои'},
      {icon:'🕯️', name:'Люстра Barovier&Toso', desc:'Murano стекло, Италия'},
    ],
    reviews: [
      {name:'Анна К.', role:'ЖК «Золотые ключи»', text:'Живём как в дворце! Каждая деталь продумана до мелочей.', img:'images/client_avatar1.png'},
    ]
  },

  // ══════ 4-ROOM ══════
  {
    id: 'four-minimalism',
    rooms: 4,
    style: 'minimalism',
    title: 'Четырёхкомнатная — Минимализм',
    shortDesc: 'Просторный минимализм для большой семьи с широкими горизонтами.',
    desc: 'В четырёхкомнатной квартире минимализм позволяет раскрыться по-настоящему. Каждой комнате своя роль, единая цветовая система и продуманные маршруты движения.',
    price: 'от 1 600 000 ₽',
    priceVal: 1600000,
    term: '5–7 месяцев',
    area: 'от 110 м²',
    image: 'images/project_studio.png',
    images: ['images/project_studio.png','images/hero_interior.png','images/about_interior.png','images/project_loft.png'],
    features: ['Полный дизайн-проект','Мастер-спальня с гардеробной','2 детские комнаты','Home-office зона','Кухня-остров','Авторский надзор'],
    materials: [
      {icon:'🪵', name:'Паркет из ясеня', desc:'Косая елочка, 120×500'},
      {icon:'🎨', name:'Veneziano штукатурка', desc:'Прихожая и гостиная'},
      {icon:'💡', name:'Artemide Тolomeo', desc:'Дизайнерские светильники'},
      {icon:'🛁', name:'Aquaton Legno', desc:'Мебель для ванных комнат'},
    ],
    reviews: [
      {name:'Дмитрий Р.', role:'ЖК «Поколение»', text:'110 кв в одном стиле. Ни одного лишнего элемента!', img:'images/client_avatar2.png'},
    ]
  },
  {
    id: 'four-scandinavian',
    rooms: 4,
    style: 'scandinavian',
    title: 'Четырёхкомнатная — Скандинавский',
    shortDesc: 'Большой скандинавский дом с теплом для всей семьи.',
    desc: 'Четырёхкомнатная квартира в скандинавском стиле — это пространство, где каждый член семьи найдёт своё место. Детские комнаты, мастер-спальня, открытая гостиная.',
    price: 'от 1 750 000 ₽',
    priceVal: 1750000,
    term: '5–8 месяцев',
    area: 'от 115 м²',
    image: 'images/project_scandi.png',
    images: ['images/project_scandi.png','images/project_two_room.png','images/hero_interior.png','images/about_interior.png'],
    features: ['Дизайн 4 комнат + кухня','2 детские с учётом возраста','Скандинавская мебель премиум','Тёплые полы везде','Умное освещение','Авторский надзор'],
    materials: [
      {icon:'🌿', name:'Дуб натуральный', desc:'Паркет Haro Parquet 4000'},
      {icon:'🧶', name:'Натуральная шерсть', desc:'Ковры и текстиль'},
      {icon:'🪴', name:'Биофитостена', desc:'Стабилизированные растения'},
      {icon:'💡', name:'Vibia Wirering', desc:'Линейное освещение'},
    ],
    reviews: [
      {name:'Михаил П.', role:'ЖК «Сколково Парк»', text:'Четыре комнаты — четыре разных характера, но единый дух. Браво!', img:'images/client_avatar2.png'},
    ]
  },
  {
    id: 'four-modern',
    rooms: 4,
    style: 'modern',
    title: 'Четырёхкомнатная — Современный стиль',
    shortDesc: 'Флагманский современный проект с полным оснащением.',
    desc: 'Современный стиль в четырёхкомнатной квартире — вершина наших возможностей. Умный дом, кинозал, профессиональная кухня, spa-ванная.',
    price: 'от 2 100 000 ₽',
    priceVal: 2100000,
    term: '6–9 месяцев',
    area: 'от 120 м²',
    image: 'images/project_two_room.png',
    images: ['images/project_two_room.png','images/hero_interior.png','images/project_loft.png','images/about_interior.png'],
    features: ['Умный дом полный','Домашний кинозал','SPA-ванная комната','Профессиональная кухня','Home-office','Авторский надзор'],
    materials: [
      {icon:'💡', name:'Crestron Home OS 3', desc:'Полная автоматизация'},
      {icon:'🎬', name:'Проектор Epson 4K', desc:'Кинозал 120" экран'},
      {icon:'🛁', name:'Jacuzzi Aquasoul', desc:'SPA-ванна с гидромассажем'},
      {icon:'🍳', name:'Miele Generation 7000', desc:'Встроенная техника'},
    ],
    reviews: [
      {name:'Анна М.', role:'ЖК «Neva Towers»', text:'Это не квартира — это произведение искусства. Хочется не выходить!', img:'images/client_avatar1.png'},
    ]
  },
  {
    id: 'four-loft',
    rooms: 4,
    style: 'loft',
    title: 'Четырёхкомнатная — Лофт',
    shortDesc: 'Монументальный лофт для ценителей пространства и свободы.',
    desc: 'Четырёхкомнатный лофт — редкое и выдающееся пространство. Это место для творчества, жизни и вдохновения. Каждая деталь — часть большой истории.',
    price: 'от 1 900 000 ₽',
    priceVal: 1900000,
    term: '6–8 месяцев',
    area: 'от 120 м²',
    image: 'images/project_loft.png',
    images: ['images/project_loft.png','images/project_two_room.png','images/hero_interior.png','images/about_interior.png'],
    features: ['Открытая планировка','Антресольный этаж','Кухня ресторанного класса','Ателье / мастерская','Металлические лестницы','Авторский надзор'],
    materials: [
      {icon:'🧱', name:'Кирпич Vandersanden', desc:'Бельгийский клинкер'},
      {icon:'⚙️', name:'Сталь Corten', desc:'Фасады мебели и декор'},
      {icon:'🪵', name:'Слэбы из тика', desc:'Столы и полки ручной работы'},
      {icon:'💡', name:'Трековое освещение', desc:'Eutrac 3-phase Nordic Aluminium'},
    ],
    reviews: [
      {name:'Екатерина С.', role:'Апартаменты «Даниловская»', text:'Лофт на 4 комнаты — это мечта, ставшая реальностью. Спасибо DesignPro!', img:'images/client_avatar3.png'},
    ]
  },
  {
    id: 'four-neoclassic',
    rooms: 4,
    style: 'neoclassic',
    title: 'Четырёхкомнатная — Неоклассика',
    shortDesc: 'Эталон роскоши — неоклассический дворец в современном доме.',
    desc: 'Четырёхкомнатная неоклассика — наш флагманский проект премиум-класса. Каждая комната — шедевр. Итальянские материалы, ручная работа, авторский дизайн.',
    price: 'от 2 800 000 ₽',
    priceVal: 2800000,
    term: '7–10 месяцев',
    area: 'от 130 м²',
    image: 'images/project_neoclassic.png',
    images: ['images/project_neoclassic.png','images/project_two_room.png','images/hero_interior.png','images/about_interior.png'],
    features: ['Лепнина ручной работы','Итальянский мрамор везде','Мебель Boca do Lobo','Роспись потолков','Антикварный декор','Авторский надзор'],
    materials: [
      {icon:'🏛️', name:'Мрамор Statuario', desc:'Итальянский, полировка'},
      {icon:'✨', name:'Позолота листовая', desc:'Детали мебели, молдинги'},
      {icon:'🖼️', name:'Художественная роспись', desc:'Потолки и ниши, фреска'},
      {icon:'🧶', name:'Шёлк и кашемир', desc:'Шторы, текстиль Hermès'},
    ],
    reviews: [
      {name:'Анна К.', role:'ЖК «Пресня Сити»', text:'Это лучшее, что мы видели. Цена оправдана на 200%. Истинная роскошь!', img:'images/client_avatar1.png'},
    ]
  }
];
